// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int nTimes = Integer.parseInt(args[0]);
		int count1 = 0;
		int count2 = 0;	
		for (int i = 1; i <= nTimes; i++){
			double randomNumber = Math.random();
			if(randomNumber > 0.5){
				count1++;
			} else {
				count2++;
			}
		}
		double ratio = (double) count1 / count2;
		if (ratio > 1) {
			ratio = count2 / count1;
		}
		System.out.println("> 0.5: " + count1 + " times");
		System.out.println("<= 0.5: " + count2 + " times");
		System.out.println("Ratio: " + ratio);
	}
}
